version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - ./app:/app

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: crosDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
